name: swiftformat
on:
  pull_request:
    paths:
      - ".github/workflows/swiftformat.yml"
      - "**/*.swift"
  workflow_dispatch:
permissions:
  contents: read
jobs:
  swiftformat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: swiftformat
        env:
          # renovate: datasource=docker depName=ghcr.io/nicklockwood/swiftformat
          SWIFTFORMAT_VERSION: 0.54.6
        run: docker run --rm --volume=.:/workspace --env GITHUB_WORKSPACE=/workspace ghcr.io/nicklockwood/swiftformat:${SWIFTFORMAT_VERSION} /workspace --lint --lenient --reporter github-actions-log
