name: swiftformat
on:
  pull_request:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '**/*.swift'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  swiftformat:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cyberbeni/swiftformat:github_actions_fix
    steps:
    - uses: actions/checkout@v4
    - name: swiftformat
      run: swiftformat . --lint --lenient
